### **Chapter6 튜플과 딕셔너리 - 연습문제**

<p>■ 회사 쇼핑몰 고객의 아이디에 부여된 마일리지 포인트를 딕셔너리에 저장하여 관리하고자 한다. 다음 물음에 답하시오(1번~4번문제)

<p>아이디 : kim99, lee66, han55, hong77, hwang33</p>
<p>마일리지 포인트 : 12000, 11000, 3000, 5000, 18000</p>



---

### 1. 위의 표에 나타난 아이디와 마일리지 포인트를 딕셔너리에 저장한 다음 출력하는 프로그램을 작성하시오.

<p><실행 결과></p>
<p>1. 아이디 : kim99, 마일리지 : 12000점</p>
<p>2. 아이디 : lee66, 마일리지 : 11000점</p>
<p>3. 아이디 : han55, 마일리지 : 3000점</p>
<p>4. 아이디 : hong77, 마일리지 : 5000점</p>
<p>5. 아이디 : hwang33, 마일리지 : 18000점</p>

In [3]:
customer = {'kim99': 12000, 'lee66': 11000, 'han55': 3000, 'hong77': 5000, 'hwang33': 18000}
i = 1

for key in customer:
  print('%d. 아이디 : %s, 마일리지 : %d점' % (i, key, customer[key]))

  i += 1

1. 아이디 : kim99, 마일리지 : 12000점
2. 아이디 : lee66, 마일리지 : 11000점
3. 아이디 : han55, 마일리지 : 3000점
4. 아이디 : hong77, 마일리지 : 5000점
5. 아이디 : hwang33, 마일리지 : 18000점

### 2. 아이디 'han55'의 마일리지를 5000점으로 업데이트하고 업데이트된 정보를 출력하는 프로그램을 작성하시오.

<p><실행 결과></p>
<p>han55님의 마일리지가 5000점으로 수정 되었습니다.</p>

In [6]:
customer = {'kim99': 12000, 'lee66': 11000, 'han55': 3000, 'hong77': 5000, 'hwang33': 18000}

for key in customer:
  if key == 'han55':
    customer[key] = 5000
    print('%s님의 마일리지가 %d점으로 수정 되었습니다.' %(key, customer[key]))

han55님의 마일리지가 5000점으로 수정 되었습니다.

### 3. 딕셔너리에 아이디 'jang88'과 마일리지 7000을 추가한 다음 전체 딕셔너리와 추가된 데이터를 출력하는 프로그램을 작성하시오.

<p><실행 결과></p>
<p>전체 딕셔너리 :  {'kim99': 12000, 'lee66': 11000, 'han55': 3000, 'hong77': 5000, 'hwang33': 18000, 'jang88': 7000}</p>
<p>jang88님의 마일리지(7000점)가 추가 되었습니다.</p>

In [11]:
customer = {'kim99': 12000, 'lee66': 11000, 'han55': 3000, 'hong77': 5000, 'hwang33': 18000}

customer['jang88'] = 7000

print('전체 딕셔너리 : ', customer)

for key in customer:
  if key == 'jang88':
    print('%s님의 마일리지(%d점)가 추가 되었습니다.' %(key, customer[key]))

전체 딕셔너리 :  {'kim99': 12000, 'lee66': 11000, 'han55': 3000, 'hong77': 5000, 'hwang33': 18000, 'jang88': 7000}
jang88님의 마일리지(7000점)가 추가 되었습니다.

### 4. 딕셔너리에서 가장 높은 마일리지를 찾아서 출력하는 프로그램을 작성하시오.

<p><실행 결과></p>
<p>hwang33님의 18000점이 가장 높은 점수입니다.</p>

In [17]:
customer = {'kim99': 12000, 'lee66': 11000, 'han55': 3000, 'hong77': 5000, 'hwang33': 18000}

max_value = 0
max_customer = ''

for key in customer:
  if max_value <= customer[key]:
    max_customer = key
    max_value = customer[key]

print('%s님의 %d점이 가장 높은 점수입니다.' %(max_customer, max_value))

hwang33님의 18000점이 가장 높은 점수입니다.

### ■ 다음은 어느 지역의 일주일 간의 최고 기온을 나타낸 것이다. 다음 물음에 답하시오.(5~8번 문제)

<p>요일 : 월, 화, 수, 목, 금, 토, 일</p>
<p>최고 기온 : 25.5, 28.3, 33.2, 32.1, 17.3, 35.3, 33.3</p>

### 5. 표의 데이터를 딕셔너리에 저장한 다음 출력하는 프로그램을 작성하시오.

<p><실행 결과></p>
<img src = "https://drive.google.com/uc?id=1XZ9qEMSu42LeAk7nf32XTI55CFsK2qXA" height = 60% width = 60%>

In [23]:
week_temp = {'월': 25.5, '화':28.3, '수': 33.2, '목': 32.1, '금':17.3, '토': 35.3, '일': 33.3}

print('-' * 45)

for key in week_temp:
  print('  %s  ' % key, end = '')

print()
print('-' * 45)

for key in week_temp:
  print(' %.1f ' % week_temp[key], end = '')

print()
print('-' * 45)

---------------------------------------------
  월    화    수    목    금    토    일
---------------------------------------------
 25.5  28.3  33.2  32.1  17.3  35.3  33.3
---------------------------------------------

### 6. 딕셔너리에서 주중 가장 낮은 최고 기온을 찾아서 출력하는 프로그램을 작성하시오.

<p><실행 결과></p>

In [28]:
week_temp = {'월': 25.5, '화':28.3, '수': 33.2, '목': 32.1, '금':17.3, '토': 35.3, '일': 33.3}

min_value = 100

for key in week_temp:
  if min_value >= week_temp[key]:
    min_value = week_temp[key]

print('가장 낮은 최고 기온 : %.1f°' % min_value)

가장 낮은 최고 기온 : 17.3°